export const info={
  docs:['Documentation','Big roadmap: one shared documentation engine.',['Usage steps, parameters and a short demo for every tool.','Separate product guides for ARQO, AutoCAD, Rhino and Grasshopper.','Release notes and known limits.']],
  downloads:['Downloads & updates','Big roadmap: per-product releases on a shared update system.',['Development, Alpha, Beta, RC and Stable channels for ARQO.','Product version, change list and compatibility.','No public SketchUp plugin download yet.']],
  support:['Support centre','Big roadmap: documentation, issue reports and support plans.',['Tool guides and frequently asked questions.','Known issues and fixes per release.','Logs are shared only with your permission; your model is never uploaded automatically.']],
  account:['Account & licences','Tools and complete packages in one account.',['Each of the 40 tools is a separate product with its own licence.','Several single purchases and the complete package combine in one ARQO installation.','Upgrade from single tools to the complete package; pricing terms are not set yet.','This screen is not connected to a real account or licence service.']],
  autocad:['CADPILOT / AutoCAD',"Working name. The product family that follows ARQO's commercial validation.",['First tools: CAD Doctor, Dimension Guardian and Geometry Healer.','DWG Clean, Layer Intelligence, Block Intelligence and Project Delivery.','Ask CAD and broader drawing intelligence in later stages.']],
  rhino:['RHINOPILOT / Rhino','Working name. Geometry intelligence and fabrication readiness.',['Geometry Doctor, Geometry Healer and Model Cleaner.','Fabrication Check, Smart Unroll and numbering.','A GH Doctor link grown from the Rhino product.']],
  grasshopper:['Grasshopper product family','Modules grown from Rhino become independent when they are ready.',['GH Doctor: root-cause analysis for definition errors.','Copilot, Definition Optimizer and Data Tree Inspector.','Reverse Parametric, Batch Bake and fabrication tools.']]
};
