export const info={
  docs:['Dokümantasyon','Büyük roadmap: ortak dokümantasyon motoru.',['Her araç için kullanım adımları, parametreler ve kısa demo.','ARQO, AutoCAD, Rhino ve Grasshopper için ayrı ürün rehberleri.','Sürüm notları ve bilinen sınırlar.']],
  downloads:['İndirme & güncellemeler','Büyük roadmap: ürünlere özel sürümler ve ortak güncelleme altyapısı.',['ARQO için geliştirme, Alpha, Beta, RC ve Stable kanalları.','Ürün sürümü, değişiklik listesi ve uyumluluk bilgisi.','Henüz indirilebilir bir SketchUp eklentisi üretilmedi.']],
  support:['Destek merkezi','Büyük roadmap: dokümantasyon, sorun bildirimi ve destek paketi.',['Araç kullanım rehberleri ve sık sorulan sorular.','Bilinen sorunlar ve sürüm bazında çözümler.','İzinli log paylaşımı; modelin otomatik sunucuya yüklenmemesi.']],
  account:['Hesap & lisanslar','Tek hesapta araçlar ve tam paketler.',['40 aracın her biri ayrı ürün ve ayrı lisans hakkı.','Birkaç tekil satın alma ve tam paket aynı ARQO kurulumunda birleşir.','Araçlardan tam pakete yükseltme; fiyatlandırma koşulları henüz belirlenmedi.','Bu ekran gerçek hesap veya lisans servisine bağlı değildir.']],
  autocad:['CADPILOT / AutoCAD','Çalışma adı. ARQO ticari doğrulamasından sonraki ürün ailesi.',['İlk araçlar: CAD Doctor, Dimension Guardian ve Geometry Healer.','DWG Clean, Layer Intelligence, Block Intelligence ve Project Delivery.','Ask CAD ve daha geniş çizim zekâsı sonraki aşamalar.']],
  rhino:['RHINOPILOT / Rhino','Çalışma adı. Geometri zekâsı ve üretime hazırlık.',['Geometry Doctor, Geometry Healer ve Model Cleaner.','Fabrication Check, Smart Unroll ve numaralandırma.','Rhino ürününden gelişen GH Doctor bağlantısı.']],
  grasshopper:['Grasshopper ürün ailesi','Rhino’dan gelişen modüller uygun olduğunda bağımsızlaşır.',['GH Doctor: definition hata kök neden analizi.','Copilot, Definition Optimizer ve Data Tree Inspector.','Reverse Parametric, Batch Bake ve fabrication araçları.']]
};
